# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration', '0005_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travel_from', models.DateTimeField(auto_now_add=True)),
                ('travel_to', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_registration.User')),
            ],
        ),
    ]
