# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='travel_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='travels',
            name='travel_to',
            field=models.DateTimeField(null=True),
        ),
    ]
