# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0005_user_dob'),
        ('travels', '0002_auto_20161227_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='travelers',
            field=models.ManyToManyField(to='login_registration.User'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_traveler', to='login_registration.User'),
        ),
    ]
