# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 20:45
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    Travels = apps.get_model("travels", "Travels")
    for travels in Travels.objects.all():
        travels.travelers.add(travels.traveler)

class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20170106_0028'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
