# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20170106_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='traveler',
        ),
    ]
