# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='book_id',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
