# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0002_auto_20161222_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='author',
            field=models.CharField(default='somestring', max_length=45),
        ),
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='sometitle', max_length=45),
        ),
    ]
