# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0003_auto_20161222_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
