# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0006_auto_20161223_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='reviewer',
        ),
    ]
