# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0004_auto_20161223_0245'),
        ('book_review', '0007_remove_reviews_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_registration.User'),
            preserve_default=False,
        ),
    ]
